ALTER TABLE organization_subscriptions
ADD COLUMN IF NOT EXISTS price_paid NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS billing_cycle VARCHAR(20),
ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMP WITH TIME ZONE;
